// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9ejVU0th-_Xm5zJleSUTcEfSL3ibwk54',
    appId: '1:936648750837:web:f3733215e9d918242b77bc',
    messagingSenderId: '936648750837',
    projectId: 'newsapp-498ba',
    authDomain: 'newsapp-498ba.firebaseapp.com',
    storageBucket: 'newsapp-498ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQzPtZfe-IqKlFz7ARrptIaLx9-UCBkCE',
    appId: '1:936648750837:android:d6a38c0c1e3121ec2b77bc',
    messagingSenderId: '936648750837',
    projectId: 'newsapp-498ba',
    storageBucket: 'newsapp-498ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKR6eUDhBMH0CmuuXEoNzm3nLQRM3z1v8',
    appId: '1:936648750837:ios:9ccf85ecac7fe8392b77bc',
    messagingSenderId: '936648750837',
    projectId: 'newsapp-498ba',
    storageBucket: 'newsapp-498ba.appspot.com',
    androidClientId: '936648750837-7cca8laim8m51fbv9cq4lmqhl9pi4963.apps.googleusercontent.com',
    iosClientId: '936648750837-ej8gmadj8eaa7vo68pkjej821253qu5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.play',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKR6eUDhBMH0CmuuXEoNzm3nLQRM3z1v8',
    appId: '1:936648750837:ios:9ccf85ecac7fe8392b77bc',
    messagingSenderId: '936648750837',
    projectId: 'newsapp-498ba',
    storageBucket: 'newsapp-498ba.appspot.com',
    androidClientId: '936648750837-7cca8laim8m51fbv9cq4lmqhl9pi4963.apps.googleusercontent.com',
    iosClientId: '936648750837-ej8gmadj8eaa7vo68pkjej821253qu5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.play',
  );
}
